include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - build/**
  
  language:
    strict-casts: true
    strict-inference: false  # SDK geliştirme için gevşetildi
    strict-raw-types: false  # SDK geliştirme için gevşetildi

linter:
  rules:
    # SDK için önemli kurallar açık bırakıldı
    public_member_api_docs: false
    prefer_relative_imports: false  # package: imports için gevşetildi
    avoid_print: false  # Debug amaçlı print'ler için
    lines_longer_than_80_chars: false  # Modern ekranlar için
    
    # Code quality kuralları açık
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_lambdas: true
    use_super_parameters: true
    
    # Cosmetic kurallar gevşetildi
    eol_at_end_of_file: false
    unnecessary_breaks: false
    sort_pub_dependencies: false
    
    # SDK geliştirme için gevşetilen kurallar
    avoid_dynamic_calls: false  # API response parsing için gerekli