targets:
  $default:
    builders:
      json_serializable:
        options:
          checked: true
          create_factory: true
          create_to_json: true
          any_map: false
          explicit_to_json: true
          generic_argument_factories: true
          
      freezed:
        options:
          copyWith: true
          equal: true
          from_json: true
          to_json: true
          
      retrofit_generator:
        options:
          null_serializable: true