name: prodobit_flutter_sdk
description: Flutter SDK for Prodobit framework - Build manufacturing and business applications with modern Flutter patterns
version: 0.6.8
homepage: https://github.com/prodobit/prodobit
repository: https://github.com/prodobit/prodobit
issue_tracker: https://github.com/prodobit/prodobit/issues

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Networking & HTTP
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.3.1
  
  # JSON Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  
  # State Management (Modern Riverpod)
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Storage & Caching
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Error Handling & Logging
  logger: ^2.3.0
  stack_trace: ^1.11.1
  
  # Utilities
  equatable: ^2.0.5
  collection: ^1.18.0
  meta: ^1.12.0
  
  # Reactive Programming
  rxdart: ^0.27.7
  
  # File Handling
  mime: ^1.0.5
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.4.0
  
  # Analysis & Linting
  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0
  
  # Testing
  mockito: ^5.4.4
  mocktail: ^1.0.3

flutter:
  # No UI components needed for SDK