name: Flutter SDK CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'packages/flutter-sdk/**'
      - '.github/workflows/flutter.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'packages/flutter-sdk/**'
      - '.github/workflows/flutter.yml'

jobs:
  test:
    name: Test Flutter SDK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true
          
      - name: Get Flutter dependencies
        working-directory: packages/flutter-sdk
        run: flutter pub get
        
      - name: Verify formatting
        working-directory: packages/flutter-sdk
        run: flutter format --set-exit-if-changed .
        
      - name: Analyze code
        working-directory: packages/flutter-sdk
        run: flutter analyze --fatal-infos
        
      - name: Run tests
        working-directory: packages/flutter-sdk
        run: flutter test --coverage
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: packages/flutter-sdk/coverage/lcov.info
          flags: flutter-sdk
          name: flutter-sdk
          
  build:
    name: Build Flutter SDK
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true
          
      - name: Get Flutter dependencies
        working-directory: packages/flutter-sdk
        run: flutter pub get
        
      - name: Run code generation
        working-directory: packages/flutter-sdk
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
        
      - name: Check for package issues
        working-directory: packages/flutter-sdk
        run: flutter pub publish --dry-run
        
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build TypeScript SDK
        run: pnpm build --filter=@prodobit/sdk
        
      - name: Get Flutter dependencies
        working-directory: packages/flutter-sdk
        run: flutter pub get
        
      - name: Run integration tests
        working-directory: packages/flutter-sdk
        run: flutter test test/integration/